name: Test and Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    - name: Publish package on JSR
      run: npx jsr publish
    - uses: actions/setup-node@master
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install, Build, and Test
      run: |
        npm install
        npm test
        npm run build
    - name: Publish to npm
      run: |
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}